name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Updates every hour
  workflow_dispatch:              # Manual trigger
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html,css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 10
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 14
